// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: modType/modType.proto

package ModType

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ModType) Reset() {
	*x = ModType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modType_modType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModType) ProtoMessage() {}

func (x *ModType) ProtoReflect() protoreflect.Message {
	mi := &file_modType_modType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModType.ProtoReflect.Descriptor instead.
func (*ModType) Descriptor() ([]byte, []int) {
	return file_modType_modType_proto_rawDescGZIP(), []int{0}
}

func (x *ModType) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ModType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetModTypeByID
type GetModTypeByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetModTypeByIDRequest) Reset() {
	*x = GetModTypeByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modType_modType_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModTypeByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModTypeByIDRequest) ProtoMessage() {}

func (x *GetModTypeByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modType_modType_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModTypeByIDRequest.ProtoReflect.Descriptor instead.
func (*GetModTypeByIDRequest) Descriptor() ([]byte, []int) {
	return file_modType_modType_proto_rawDescGZIP(), []int{1}
}

func (x *GetModTypeByIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetModTypeByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModType *ModType `protobuf:"bytes,1,opt,name=ModType,proto3" json:"ModType,omitempty"`
}

func (x *GetModTypeByIDResponse) Reset() {
	*x = GetModTypeByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modType_modType_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModTypeByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModTypeByIDResponse) ProtoMessage() {}

func (x *GetModTypeByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modType_modType_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModTypeByIDResponse.ProtoReflect.Descriptor instead.
func (*GetModTypeByIDResponse) Descriptor() ([]byte, []int) {
	return file_modType_modType_proto_rawDescGZIP(), []int{2}
}

func (x *GetModTypeByIDResponse) GetModType() *ModType {
	if x != nil {
		return x.ModType
	}
	return nil
}

// GetModTypes
type GetModTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetModTypesRequest) Reset() {
	*x = GetModTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modType_modType_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModTypesRequest) ProtoMessage() {}

func (x *GetModTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modType_modType_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModTypesRequest.ProtoReflect.Descriptor instead.
func (*GetModTypesRequest) Descriptor() ([]byte, []int) {
	return file_modType_modType_proto_rawDescGZIP(), []int{3}
}

type GetModTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModTypes []*ModType `protobuf:"bytes,1,rep,name=ModTypes,proto3" json:"ModTypes,omitempty"`
}

func (x *GetModTypesResponse) Reset() {
	*x = GetModTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modType_modType_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModTypesResponse) ProtoMessage() {}

func (x *GetModTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modType_modType_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModTypesResponse.ProtoReflect.Descriptor instead.
func (*GetModTypesResponse) Descriptor() ([]byte, []int) {
	return file_modType_modType_proto_rawDescGZIP(), []int{4}
}

func (x *GetModTypesResponse) GetModTypes() []*ModType {
	if x != nil {
		return x.ModTypes
	}
	return nil
}

var File_modType_modType_proto protoreflect.FileDescriptor

var file_modType_modType_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2d, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x4d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x4d,
	0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x32, 0xcd, 0x01, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x26, 0x2e, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x78, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x4d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modType_modType_proto_rawDescOnce sync.Once
	file_modType_modType_proto_rawDescData = file_modType_modType_proto_rawDesc
)

func file_modType_modType_proto_rawDescGZIP() []byte {
	file_modType_modType_proto_rawDescOnce.Do(func() {
		file_modType_modType_proto_rawDescData = protoimpl.X.CompressGZIP(file_modType_modType_proto_rawDescData)
	})
	return file_modType_modType_proto_rawDescData
}

var file_modType_modType_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modType_modType_proto_goTypes = []interface{}{
	(*ModType)(nil),                // 0: modType_service.ModType
	(*GetModTypeByIDRequest)(nil),  // 1: modType_service.GetModTypeByIDRequest
	(*GetModTypeByIDResponse)(nil), // 2: modType_service.GetModTypeByIDResponse
	(*GetModTypesRequest)(nil),     // 3: modType_service.GetModTypesRequest
	(*GetModTypesResponse)(nil),    // 4: modType_service.GetModTypesResponse
}
var file_modType_modType_proto_depIdxs = []int32{
	0, // 0: modType_service.GetModTypeByIDResponse.ModType:type_name -> modType_service.ModType
	0, // 1: modType_service.GetModTypesResponse.ModTypes:type_name -> modType_service.ModType
	1, // 2: modType_service.ModTypeService.GetModTypeByID:input_type -> modType_service.GetModTypeByIDRequest
	3, // 3: modType_service.ModTypeService.GetModTypes:input_type -> modType_service.GetModTypesRequest
	2, // 4: modType_service.ModTypeService.GetModTypeByID:output_type -> modType_service.GetModTypeByIDResponse
	4, // 5: modType_service.ModTypeService.GetModTypes:output_type -> modType_service.GetModTypesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modType_modType_proto_init() }
func file_modType_modType_proto_init() {
	if File_modType_modType_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modType_modType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modType_modType_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModTypeByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modType_modType_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModTypeByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modType_modType_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modType_modType_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modType_modType_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modType_modType_proto_goTypes,
		DependencyIndexes: file_modType_modType_proto_depIdxs,
		MessageInfos:      file_modType_modType_proto_msgTypes,
	}.Build()
	File_modType_modType_proto = out.File
	file_modType_modType_proto_rawDesc = nil
	file_modType_modType_proto_goTypes = nil
	file_modType_modType_proto_depIdxs = nil
}
